# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TuNH SE 
email: nguyenhongtu.it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm just a grain of sand in the desert.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tunhse.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  tunhse

# Build settings
markdown: kramdown
